### ISSUE TITLE
Missing directory core/vendor/phpunit/phpunit/phpunit 

### ISSUE THREAD

**Issue by steffenboe** [EXXETA/wwf-plugin-donations#7]
When running the `release.sh` script, the script tries to change directory to `core/vendor/phpunit/phpunit/phpunit` (line 28/29). THis path does not exist when checking out the directory. Am i missing something?

**Comment by emschu** [comment]
Please have a look at the "Setup - Installation - Release" section of the top-level README file in this project and consider that there is a `setup.sh` script. This is also the key to issue #8.
