### ISSUE TITLE
Plugin Activation fails with UncaughtError

### ISSUE THREAD

**Issue by steffenboe** [EXXETA/wwf-plugin-donations#9]
After setting up the development environment, creating a release and copying the plugin to the wordpress plugin directory, the activiation of this plugin fails with an exception:

Fatal error: Uncaught Error: Cannot access property donations\CharityProductManager::$genericFootNotesTextDE in D:\xampp_2\htdocs\wp-content\plugins\wwf-donations-plugin\vendor\exxeta\wwf-donations-shop-banner-core\src\wwf\banner\AbstractCharityProductManager.php:55 Stack trace: #0 D:\xampp_2\htdocs\wp-content\plugins\wwf-donations-plugin\vendor\exxeta\wwf-donations-shop-banner-core\src\wwf\banner\AbstractCharityProductManager.php(46): exxeta\wwf\banner\AbstractCharityProductManager->initCampaigns() #1 D:\xampp_2\htdocs\wp-content\plugins\wwf-donations-plugin\donations\Plugin.php(55): exxeta\wwf\banner\AbstractCharityProductManager->__construct() #2 D:\xampp_2\htdocs\wp-content\plugins\wwf-donations-plugin\wwf-donations-plugin.php(29): donations\Plugin->__construct('D:\\xampp_2\\htdo...') #3 D:\xampp_2\htdocs\wp-admin\includes\plugin.php(2223): include('D:\\xampp_2\\htdo...') #4 D:\xampp_2\htdocs\wp-admin\plugins.php(175): plugin_sandbox_scrape('wwf-donations-p...') #5 {main} thrown in D:\xampp_2\htdocs\wp-content\plugins\wwf-donations-plugin\vendor\exxeta\wwf-donations-shop-banner-core\src\wwf\banner\AbstractCharityProductManager.php on line 55

My wordpress site:
WordPress Version: 5.3.6
Current WordPress Theme: Airi Child version 1.0airi
Theme Author: LA Studio - http://themeforest.net/user/LA-Studio?ref=LA-Studio
Theme URI: http://themeforest.net/user/LA-Studio/portfolio?ref=LA-Studio
PHP Version: 7.3.13
MySQL Version: 10.3.21-MariaDB
Apache Version: Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.13

After updating to wordpress 5.6, error´s still thrown.

**Comment by emschu** [comment]
Hello @steffenb91,

thank you very much for reporting this. I can reproduce this bug with php 7.3.X, but not with php 7.4.X. 

Could you please checkout the branch `feature/core-1-0-1`, run a `composer update` inside `./wp/wwf-donations-plugin/` and run the release-script again? The recent changes on this branch should fix it. If not, please let me know.

**Comment by steffenboe** [comment]
great! the fix resolved this issue, plugin activation now works!
